# Generated by Django 3.1.2 on 2020-10-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationItem',
            fields=[
                ('id_obs', models.AutoField(primary_key=True, serialize=False)),
                ('observation', models.TextField()),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedLink',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('org_name', models.CharField(max_length=50)),
            ],
        ),
    ]
